---
- name: Install Software Packages
  hosts: localhost
  become: true
  vars:
    keyring_file: "/usr/share/keyrings/hashicorp-archive-keyring.gpg"
    apt_source: "https://apt.releases.hashicorp.com"
    apt_repo: "{{ apt_source }} {{ ansible_distribution_release }} main"
   
      
  tasks:
    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Change Ubuntu package repository
      lineinfile:
        dest: /etc/apt/sources.list
        regexp: '^deb http://br.archive.ubuntu.com'
        line: 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main'
      become: true


    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present

    - name: Add user to docker group
      user:
        name: "w3ll1n9t0n"
        append: yes
        groups: docker
        state: present
  

    - name: Install Kind
      shell: >
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64 &&
        chmod +x ./kind &&
        sudo mv ./kind /usr/local/bin/kind

    - name: Install kubectl
      shell: >
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" &&
        chmod +x kubectl &&
        sudo mv kubectl /usr/local/bin/

    - name: Download and configure HashiCorp GPG key
      shell: >
        wget -O- https://apt.releases.hashicorp.com/gpg |
        gpg --dearmor |
        sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      changed_when: False

    - name: Add HashiCorp repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

    - name: Install Terraform
      apt:
        name: terraform
        state: present

    - name: Download Iriun Webcam package
      get_url:
        url: "https://iriun.gitlab.io/iriunwebcam-2.8.deb"
        dest: "/tmp/iriunwebcam-2.8.deb"

    - name: Install Iriun Webcam package
      apt:
        deb: /tmp/iriunwebcam-2.8.deb
        state: present

    - name: Install DBeaver CE
      snap:
        name: dbeaver-ce
        classic: yes

    - name: Import Microsoft GPG key
      apt_key:
        url: "https://packages.microsoft.com/keys/microsoft.asc"
        state: present

    - name: Add Visual Studio Code repository
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        state: present

    - name: Install Visual Studio Code
      apt:
        name: code
        state: latest

    - name: Install python3-pip package
      apt:
        name: python3-pip
        state: present

    - name: Download AWS CLI package
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"

    - name: Unarchive AWS CLI package
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp"

    - name: Install AWS CLI
      command: "/tmp/aws/install --update"

    - name: Install software telegram using snap
      command: snap install telegram-desktop 

    - name: Install software vlc using snap
      command: snap install vlc

    - name: Update package cache
      apt:
        update_cache: yes
